### ISSUE TITLE
Tile Entity throwing an exception

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/TestMod#4]
Not Fatal Exception

```
[01:03:16] [Server thread/ERROR] [FML]: A TileEntity type com.davoleo.testmod.block.counter.TileEntityCounter has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.davoleo.testmod.block.counter.TileEntityCounter is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.writeInternal(TileEntity.java:89) ~[TileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:80) ~[TileEntity.class:?]
	at com.davoleo.testmod.block.counter.TileEntityCounter.writeToNBT(TileEntityCounter.java:22) ~[TileEntityCounter.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:414) [AnvilChunkLoader.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:185) [AnvilChunkLoader.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunkData(ChunkProviderServer.java:214) [ChunkProviderServer.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:242) [ChunkProviderServer.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1061) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:468) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:274) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:766) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by Davoleo** [comment]
Partially fixed using the deprecated method registerTileEntity

**Comment by Davoleo** [comment]
Fixed Registring the tile entity in the GameRegistry
